Repository modelica/VehicleInterfaces, pull requests merged in 2021-10, with the labels that each got.

#97 Enable user-friendly dialog for replaceable road function
  VehicleInterfaces/Roads/Interfaces/Base.mo
Labels: enhancement, L: Roads

#98 Add CI badge (for GitHub Actions)
  README.md
Labels: CI

#101 Remove annotation versionBuild
  VehicleInterfaces/package.mo
Labels: enhancement
